In [ ]:
pip install numpy


In [ ]:
import numpy as np

In [ ]:
scalar = np.array(5)

print(scalar)
print("Shape:", scalar.shape)
print("Dimensions:", scalar.ndim)


5
Shape: ()
Dimensions: 0


In [ ]:
vector = np.array([2, 4, 6, 8])

print(vector)
print("Shape:", vector.shape)
print("Dimensions:", vector.ndim)


[2 4 6 8]
Shape: (4,)
Dimensions: 1


In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)


[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2


In [ ]:
tensor_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(tensor_3d)
print("Shape:", tensor_3d.shape)
print("Dimensions:", tensor_3d.ndim)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3


In [ ]:
print("Rank:", tensor_3d.ndim)
print("Shape:", tensor_3d.shape)
print("Size:", tensor_3d.size)



Rank: 3
Shape: (2, 2, 2)
Size: 8


In [ ]:
students = np.array([
    [8.5, 110, 1],   # Student 1
    [7.2, 102, 0],   # Student 2
    [9.0, 120, 1]    # Student 3
])

print(students)
print("Shape:", students.shape)
print("Dimensions:", students.ndim)


[[  8.5 110.    1. ]
 [  7.2 102.    0. ]
 [  9.  120.    1. ]]
Shape: (3, 3)
Dimensions: 2


In [ ]:
placement = np.array([1, 0, 1])

print(placement)
print("Shape:", placement.shape)


[1 0 1]
Shape: (3,)


In [ ]:
# Vocabulary
hi = np.array([1, 0, 0])
hello = np.array([0, 1, 0])
bye = np.array([0, 0, 1])

sentence = np.array([hi, hello])

print(sentence)
print("Shape:", sentence.shape)


[[1 0 0]
 [0 1 0]]
Shape: (2, 3)


In [ ]:
data = np.array([
    [[1,0,0], [0,1,0]],   # sentence 1
    [[0,1,0], [0,0,1]]    # sentence 2
])

print(data.shape)


(2, 2, 3)


In [ ]:
image = np.random.randint(0, 255, (224, 224, 3))

print("Shape:", image.shape)
print("Dimensions:", image.ndim)


Shape: (224, 224, 3)
Dimensions: 3


In [ ]:
video = np.random.randint(0, 255, (60, 224, 224, 3))

print("Shape:", video.shape)
print("Dimensions:", video.ndim)


Shape: (60, 224, 224, 3)
Dimensions: 4


In [ ]:
print(vector[0])
print(matrix[1][2])
print(tensor_3d[0][1][1])


2
6
4
